import type { Gift } from "../types/gift";

export const gifts: Gift[] = [
  {
    id: "panelas",
    category: "Cozinha",
    title: "Jogo de Panelas Antiaderente",
    description: "Conjunto de 5 peças com revestimento antiaderente.",
    priceInCents: 38900,
    image: "https://picsum.photos/seed/panelas/600/400",
  },
  {
    id: "jantar",
    category: "Mesa posta",
    title: "Aparelho de Jantar 20 peças",
    description: "Porcelana branca para 4 lugares.",
    priceInCents: 32900,
    image: "https://picsum.photos/seed/jantar/600/400",
  },
  {
    id: "airfryer",
    category: "Eletro",
    title: "Air Fryer 5L",
    description: "Fritadeira sem óleo digital para o dia a dia.",
    priceInCents: 45900,
    image: "https://picsum.photos/seed/airfryer/600/400",
  },
  {
    id: "cafeteira",
    category: "Eletro",
    title: "Cafeteira Elétrica",
    description: "Para os cafés da manhã preguiçosos de domingo.",
    priceInCents: 24900,
    image: "https://picsum.photos/seed/cafeteira/600/400",
  },
  {
    id: "liquidificador",
    category: "Eletro",
    title: "Liquidificador 1000W",
    description: "Potente, com copo de vidro e várias velocidades.",
    priceInCents: 19900,
    image: "https://picsum.photos/seed/liquidificador/600/400",
  },
  {
    id: "tacas",
    category: "Mesa posta",
    title: "Conjunto de Taças de Cristal",
    description: "6 taças para brindar os bons momentos.",
    priceInCents: 15900,
    image: "https://picsum.photos/seed/tacas/600/400",
  },
  {
    id: "faqueiro",
    category: "Mesa posta",
    title: "Faqueiro Inox 24 peças",
    description: "Talheres em aço inox para o dia a dia.",
    priceInCents: 17900,
    image: "https://picsum.photos/seed/faqueiro/600/400",
  },
  {
    id: "toalhas",
    category: "Banho",
    title: "Jogo de Toalhas de Banho",
    description: "Conjunto felpudo e macio de algodão.",
    priceInCents: 13900,
    image: "https://picsum.photos/seed/toalhas/600/400",
  },
  {
    id: "edredom",
    category: "Quarto",
    title: "Edredom Casal",
    description: "Aconchego garantido nas noites mais frias.",
    priceInCents: 22900,
    image: "https://picsum.photos/seed/edredom/600/400",
  },
  {
    id: "potes",
    category: "Cozinha",
    title: "Jogo de Potes Herméticos",
    description: "Organização e frescor para a despensa.",
    priceInCents: 11900,
    image: "https://picsum.photos/seed/potes/600/400",
  },
  {
    id: "tabua",
    category: "Cozinha",
    title: "Tábua de Corte de Madeira",
    description: "Madeira maciça com canaleta. Linda e útil.",
    priceInCents: 8900,
    image: "https://picsum.photos/seed/tabua/600/400",
  },
  {
    id: "aspirador",
    category: "Limpeza",
    title: "Aspirador de Pó Vertical",
    description: "Sem fio, prático para manter tudo em ordem.",
    priceInCents: 39900,
    image: "https://picsum.photos/seed/aspirador/600/400",
  },
];
